# CMake generated Testfile for 
# Source directory: G:/cnc/solvespace/solvespace-2.3_vs2005/extlib/libpng
# Build directory: G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngtest "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngtest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngtest "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngtest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngtest "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngtest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngtest "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngtest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngtest.cmake")
else()
  add_test(pngtest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-16-to-8 "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-16-to-8.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-16-to-8 "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-16-to-8.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-16-to-8 "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-16-to-8.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-16-to-8 "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-16-to-8.cmake")
else()
  add_test(pngvalid-gamma-16-to-8 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-alpha-mode "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-alpha-mode "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-alpha-mode "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-alpha-mode "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-alpha-mode.cmake")
else()
  add_test(pngvalid-gamma-alpha-mode NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-background "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-background "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-background "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-background "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-background.cmake")
else()
  add_test(pngvalid-gamma-background NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
else()
  add_test(pngvalid-gamma-expand16-alpha-mode NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-expand16-background "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-expand16-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-expand16-background "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-expand16-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-expand16-background "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-expand16-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-expand16-background "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-expand16-background.cmake")
else()
  add_test(pngvalid-gamma-expand16-background NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-expand16-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-expand16-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-expand16-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-expand16-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-expand16-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-expand16-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-expand16-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-expand16-transform.cmake")
else()
  add_test(pngvalid-gamma-expand16-transform NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-sbit "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-sbit.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-sbit "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-sbit.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-sbit "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-sbit.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-sbit "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-sbit.cmake")
else()
  add_test(pngvalid-gamma-sbit NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-threshold "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-threshold.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-threshold "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-threshold.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-threshold "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-threshold.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-threshold "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-threshold.cmake")
else()
  add_test(pngvalid-gamma-threshold NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-gamma-transform.cmake")
else()
  add_test(pngvalid-gamma-transform NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-progressive-interlace-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-progressive-interlace-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-progressive-interlace-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-progressive-interlace-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-progressive-interlace-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-progressive-interlace-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-progressive-interlace-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-progressive-interlace-standard.cmake")
else()
  add_test(pngvalid-progressive-interlace-standard NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-progressive-size "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-progressive-size.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-progressive-size "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-progressive-size.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-progressive-size "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-progressive-size.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-progressive-size "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-progressive-size.cmake")
else()
  add_test(pngvalid-progressive-size NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-progressive-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-progressive-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-progressive-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-progressive-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-progressive-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-progressive-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-progressive-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-progressive-standard.cmake")
else()
  add_test(pngvalid-progressive-standard NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-standard.cmake")
else()
  add_test(pngvalid-standard NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngvalid.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngvalid-transform.cmake")
else()
  add_test(pngvalid-transform NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-1.8-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-1.8-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-1.8-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-1.8-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-1.8-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-1.8-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-1.8-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-1.8-none.cmake")
else()
  add_test(pngstest-1.8-none NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-1.8-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-1.8-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-1.8-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-1.8-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-1.8-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-1.8-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-1.8-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-1.8-alpha.cmake")
else()
  add_test(pngstest-1.8-alpha NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-linear-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-linear-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-linear-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-linear-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-linear-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-linear-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-linear-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-linear-none.cmake")
else()
  add_test(pngstest-linear-none NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-linear-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-linear-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-linear-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-linear-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-linear-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-linear-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-linear-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-linear-alpha.cmake")
else()
  add_test(pngstest-linear-alpha NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-none-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-none-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-none-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-none-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-none-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-none-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-none-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-none-none.cmake")
else()
  add_test(pngstest-none-none NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-none-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-none-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-none-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-none-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-none-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-none-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-none-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-none-alpha.cmake")
else()
  add_test(pngstest-none-alpha NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-sRGB-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-sRGB-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-sRGB-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-sRGB-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-sRGB-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-sRGB-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-sRGB-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-sRGB-none.cmake")
else()
  add_test(pngstest-sRGB-none NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-sRGB-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-sRGB-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-sRGB-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-sRGB-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-sRGB-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-sRGB-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-sRGB-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngstest.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngstest-sRGB-alpha.cmake")
else()
  add_test(pngstest-sRGB-alpha NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-discard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-discard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-discard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-discard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-discard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-discard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-discard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-discard.cmake")
else()
  add_test(pngunknown-discard NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-IDAT "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-IDAT.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-IDAT "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-IDAT.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-IDAT "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-IDAT.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-IDAT "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-IDAT.cmake")
else()
  add_test(pngunknown-IDAT NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-if-safe "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-if-safe.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-if-safe "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-if-safe.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-if-safe "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-if-safe.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-if-safe "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-if-safe.cmake")
else()
  add_test(pngunknown-if-safe NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-sAPI "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-sAPI.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-sAPI "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-sAPI.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-sAPI "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-sAPI.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-sAPI "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-sAPI.cmake")
else()
  add_test(pngunknown-sAPI NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-save "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-save.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-save "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-save.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-save "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-save.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-save "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-save.cmake")
else()
  add_test(pngunknown-save NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-sTER "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-sTER.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-sTER "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-sTER.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-sTER "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-sTER.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-sTER "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-sTER.cmake")
else()
  add_test(pngunknown-sTER NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-vpAg "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-vpAg.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-vpAg "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-vpAg.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-vpAg "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-vpAg.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-vpAg "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngunknown.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngunknown-vpAg.cmake")
else()
  add_test(pngunknown-vpAg NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngimage-quick "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngimage.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngimage-quick.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngimage-quick "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngimage.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngimage-quick.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngimage-quick "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngimage.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngimage-quick.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngimage-quick "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngimage.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngimage-quick.cmake")
else()
  add_test(pngimage-quick NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngimage-full "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Release/pngimage.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngimage-full.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngimage-full "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/libpng16d.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/Debug/pngimage.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngimage-full.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngimage-full "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/MinSizeRel/pngimage.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngimage-full.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngimage-full "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/RelWithDebInfo/pngimage.exe" "-P" "G:/cnc/solvespace/solvespace-2.3_vs2005/Proj/extlib/libpng/tests/pngimage-full.cmake")
else()
  add_test(pngimage-full NOT_AVAILABLE)
endif()
